### PR TITLE
Add in configuration for excludedPackages

### PR DESCRIPTION
**Pull request by ckipp01**
This is a follow-up to https://github.com/scalameta/metals/pull/2012 so that users are able to customize the package exclusions.

### CODE REVIEW

**Review by kpbochenek — APPROVED** [review]
LGTM :+1:

(needs to wait for metals release?)

**Comment by ckipp01** [comment]
> LGTM 👍
> 
> (needs to wait for metals release?)

Since we are waiting for other things as well, sure. I don't think it matters _that_ much since we never release the plugin apart fro Metals anyways.

**Comment by gabro** [comment]
> I don't think it matters _that_ much since we never release the plugin apart fro Metals anyways.

It's rare, but it happened in the past and can technically happen again in case of bug fixes or VSCode-specific improvements.

**Comment by ckipp01** [comment]
> It's rare, but it happened in the past and can technically happen again in case of bug fixes or VSCode-specific improvements.

Maybe something to consider is doing a `release`, `development` branch strategy so that we could merge in features as they are added to `development` and then into `release` when we release. That way individuals that want to potentially use certain features in the Metals snapshot can use them if they build themselves. I'm not sure how common it is that someone wants to do that, but it's not the easiest to do that now.

**Comment by gabro** [comment]
It's certainly something that makes sense if we want to support that use case. For the time being I think the changes to the extension are few enough that the current "simplistic" approach still works decently.

**Pull request merged**
